FROM nginx
COPY conf/default.conf /etc/nginx/conf.d/default.conf
COPY html /usr/share/nginx/html/html
COPY css /usr/share/nginx/html/css
COPY js /usr/share/nginx/html/js
COPY files /usr/share/nginx/html/files
